#psql -d gda --username=postgres -h localhost -c "COPY gda.d_titres TO '/tmp/gda_titres.csv' WITH CSV HEADER;"
#psql -d gda --username=postgres -h localhost -c "COPY gda.p_typetr TO '/tmp/gda_typetr.csv' WITH CSV HEADER;"
#psql -d gda --username=postgres -h localhost -c "COPY gda.d_activite TO '/tmp/gda_activite.csv' WITH CSV HEADER;"
#psql -d gda --username=postgres -h localhost -c "COPY gda.d_demandeurs TO '/tmp/gda_demandeurs.csv' WITH CSV HEADER;"
#psql -d gda --username=postgres -h localhost -c "COPY gda.d_prolongation TO '/tmp/gda_prolongation.csv' WITH CSV HEADER;"
psql -d gda --username=postgres -h localhost -c "COPY gda.p_avis TO '/tmp/gda_avis.csv' WITH CSV HEADER;"
